# Generated by Django 3.2.18 on 2023-06-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.CharField(blank=True, max_length=100)),
                ('category_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_description', models.CharField(blank=True, max_length=100)),
                ('course_image', models.ImageField(blank=True, default='default_image.png', upload_to='course_images')),
                ('course_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.category')),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100, unique=True)),
                ('exam_description', models.CharField(blank=True, max_length=100)),
                ('exam_start_date', models.DateTimeField(blank=True)),
                ('exam_duration', models.IntegerField(blank=True)),
                ('exam_status', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('exam_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.course')),
            ],
            options={
                'db_table': 'exam',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=100, unique=True)),
                ('question_text', models.CharField(blank=True, max_length=200)),
                ('option1', models.CharField(blank=True, max_length=100)),
                ('option2', models.CharField(blank=True, max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100)),
                ('option4', models.CharField(blank=True, max_length=100)),
                ('correct_answer', models.CharField(blank=True, max_length=100)),
                ('question_status', models.BooleanField(default=True)),
                ('question_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.exam')),
            ],
            options={
                'db_table': 'question',
                'managed': True,
            },
        ),
    ]
