# Generated by Django 4.2.2 on 2023-08-05 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"managed": True},
        ),
    ]
