# Generated by Django 4.2.2 on 2023-06-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='courses.gif', upload_to='course_images'),
        ),
    ]
