# Generated by Django 4.2.2 on 2023-08-05 12:28

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_alter_question_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_exam",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.exam",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.TextField(default=1, verbose_name=builtins.max),
            preserve_default=False,
        ),
    ]
