# Generated by Django 4.2.2 on 2023-07-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_examattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
    ]
