# Generated by Django 4.2.2 on 2023-08-05 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_question_question_exam_question_question_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_image",
        ),
    ]
